oap/urls.py
from django.conf import settings
from django.urls import include, path
from django.contrib import admin

from wagtail.admin import urls as wagtailadmin_urls
from wagtail import urls as wagtail_urls
from wagtail.documents import urls as wagtaildocs_urls

from search import views as search_views

urlpatterns = [
    path("django-admin/", admin.site.urls),
    path("admin/", include(wagtailadmin_urls)),
    path("documents/", include(wagtaildocs_urls)),
    path("search/", search_views.search, name="search"),
]


if settings.DEBUG:
    from django.conf.urls.static import static
    from django.contrib.staticfiles.urls import staticfiles_urlpatterns

    # Serve static and media files from development server
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns = urlpatterns + [
    # For anything not caught by a more specific rule above, hand over to
    # Wagtail's page serving mechanism. This should be the last pattern in
    # the list:
    path("", include(wagtail_urls)),
    # Alternatively, if you want Wagtail pages to be served from a subpath
    # of your site, rather than the site root:
    #    path("pages/", include(wagtail_urls)),
]

tutorial/blog/urls.py
from django.urls import re_path
from django.views.generic import ListView, DateDetailView

from blog.models import Post


app_name = 'blog'


urlpatterns = [
    re_path(
        r'^$',
        ListView.as_view(queryset=Post.objects.published(), paginate_by=3),
        name='post-list'),
    re_path(
        r'^(?P<year>\d{4})/(?P<month>\w{3})/(?P<day>\d{2})/(?P<slug>[-\w]+)/$',
        DateDetailView.as_view(date_field="publish", model=Post),
        name='post-detail')
]

tutorial/tutorial/urls.py
from django.conf import settings
from django.urls import include, path
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.views.generic import TemplateView


urlpatterns = [
    path(r'admin/', admin.site.urls),
    path(r'blog/', include('blog.urls', namespace='blog')),
    path(r'', TemplateView.as_view(template_name="home.html"),
        name='homepage'),
]


if settings.DEBUG:
    urlpatterns += staticfiles_urlpatterns()

home/models.py
from django.db import models
from modelcluster.fields import ParentalKey
from wagtail.admin.panels import FieldPanel, InlinePanel
from wagtail.fields import RichTextField
from wagtail.models import Page, Orderable
from django.db import models
from django.utils.translation import gettext_lazy as _

class HomePage(Page):
    class Meta:
        verbose_name = "home page"

    hero_title = RichTextField(blank=True)
    sub_title = models.CharField(max_length=200, blank=True)

    content_panels = Page.content_panels + [
        FieldPanel('title'),
        FieldPanel('hero_title'),
        FieldPanel('sub_title'),
        InlinePanel('gallery_images', label=_("Gallery images")),
    ]


class ImageGallery(Orderable):
    page = ParentalKey(HomePage, on_delete=models.CASCADE, related_name='gallery_images')
    image = models.ForeignKey(
        'wagtailimages.Image', on_delete=models.CASCADE, related_name='+'
    )
    caption = models.CharField(blank=True, max_length=250)

    panels = [
        FieldPanel('image'),
        FieldPanel('caption'),
    ]

tutorial/blog/models.py
from django.db import models
from django.urls import reverse
from django.utils import timezone


class PostManager(models.Manager):
    def published(self):
        return self.get_queryset().filter(status="PUB",
                                          publish__lte=timezone.now())


class Post(models.Model):
    STATUS_CHOICES = (
        ('DRAFT', 'Draft'),
        ('PUB', 'Published'),
    )
    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250, unique_for_date='publish')
    body = models.TextField()
    status = models.CharField(max_length=5, choices=STATUS_CHOICES,
                              default="DRAFT")
    allow_comments = models.BooleanField('allow comments', default=True)
    publish = models.DateTimeField(default=timezone.now)
    objects = PostManager()

    class Meta:
        ordering = ('-publish',)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:post-detail',
                       kwargs={'year': self.publish.year,
                               'month': self.publish.strftime('%b'),
                               'day': self.publish.strftime('%d'),
                               'slug': self.slug})

user/models.py
# Create your models here.
# myapp/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class User(AbstractUser):
    country = models.CharField(verbose_name='country', max_length=2, default='NL',
                               null=False, blank=False)
    # status = models.ForeignKey(MembershipStatus, on_delete=models.SET_NULL, null=True, default=1)

user/forms.py
# myapp/forms.py
from django import forms
from django.utils.translation import gettext_lazy as _

from wagtail.users.forms import UserEditForm, UserCreationForm


class CustomUserEditForm(UserEditForm):
    country = forms.CharField(required=True, label=_("Country"))
    # status = forms.ModelChoiceField(queryset=MembershipStatus.objects, required=True, label=_("Status"))


class CustomUserCreationForm(UserCreationForm):
    country = forms.CharField(required=True, label=_("Country"))
    # status = forms.ModelChoiceField(queryset=MembershipStatus.objects, required=True, label=_("Status"))

search/views.py
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from django.template.response import TemplateResponse

from wagtail.models import Page

# To enable logging of search queries for use with the "Promoted search results" module
# <https://docs.wagtail.org/en/stable/reference/contrib/searchpromotions.html>
# uncomment the following line and the lines indicated in the search function
# (after adding wagtail.contrib.search_promotions to INSTALLED_APPS):

# from wagtail.contrib.search_promotions.models import Query


def search(request):
    search_query = request.GET.get("query", None)
    page = request.GET.get("page", 1)

    # Search
    if search_query:
        search_results = Page.objects.live().search(search_query)

        # To log this query for use with the "Promoted search results" module:

        # query = Query.get(search_query)
        # query.add_hit()

    else:
        search_results = Page.objects.none()

    # Pagination
    paginator = Paginator(search_results, 10)
    try:
        search_results = paginator.page(page)
    except PageNotAnInteger:
        search_results = paginator.page(1)
    except EmptyPage:
        search_results = paginator.page(paginator.num_pages)

    return TemplateResponse(
        request,
        "search/search.html",
        {
            "search_query": search_query,
            "search_results": search_results,
        },
    )

user/views.py
from django.shortcuts import render

# Create your views here.

home/templates/home/hero_section.html
{% load i18n wagtailcore_tags static %}

<div class="container">
    <div class="row">
        <h1 class="display-1 text-center fw-bold" style="color: #000000a2;">{{ page.hero_title | richtext }}</h1>
    </div>
    <div class="row">
        <p class="lead text-center display-5">{{ page.sub_title }}</p>
    </div>
    <div class="d-grid col-4 mx-auto pt-5">
        <button class="btn btn-outline-dark fs-2 fw-medium" type="button">Plaats een Oproep</button>
    </div>
    <div class="d-grid mx-auto pt-5">
        <div class="hero-section"></div>
    </div>
</div>

home/templates/home/home_page.html
{% extends "base.html" %}
{% load static %}

{% block body_class %}template-homepage{% endblock %}

{% block extra_css %}{% endblock extra_css %}

{% block content %}
<div class="container-fluid vh-100">

    {% include 'home/nav_bar.html' %}

    {% include 'home/hero_section.html' %}
</div>

{% endblock content %}

home/templates/home/nav_bar.html
<nav class="navbar navbar-expand-lg rounded vh-10" aria-label="Twelfth navbar example" style="background-color: linear-gradient(180deg, #f8b500 20%, #fceabb 50%);">
    <div class="container-fluid">
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarsExample10" aria-controls="navbarsExample10" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse justify-content-md-center" id="navbarsExample10">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link active link-light" aria-current="page" href="#">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link link-light" href="#">Hoe het werkt</a>
          </li>
          <li class="nav-item">
            <a class="nav-link link-light" aria-disabled="true">Contact</a>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle link-light" href="#" data-bs-toggle="dropdown" aria-expanded="false">Dropdown</a>
            <ul class="dropdown-menu">
              <li><a class="dropdown-item" href="#">Action</a></li>
              <li><a class="dropdown-item" href="#">Another action</a></li>
              <li><a class="dropdown-item" href="#">Something else here</a></li>
            </ul>
          </li>
        </ul>
      </div>
    </div>
  </nav>
  

oap/templates/base.html
{% load static wagtailcore_tags %}
{% load bootstrap5 %}

<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <title>
        {% block title %}
        {% if page.seo_title %}{{ page.seo_title }}{% else %}{{ page.title }}{% endif %}
        {% endblock %}
        {% block title_suffix %}
        {% wagtail_site as current_site %}
        {% if current_site and current_site.site_name %}- {{ current_site.site_name }}{% endif %}
        {% endblock %}
    </title>
    {% if page.search_description %}
    <meta name="description" content="{{ page.search_description }}" />
    {% endif %}
    <meta name="viewport" content="width=device-width, initial-scale=1" />

    {# Force all links in the live preview panel to be opened in a new tab #}
    {% if request.in_preview_panel %}
    <base target="_blank">
    {% endif %}

    {# Global stylesheets #}
    <link rel="stylesheet" type="text/css" href="{% static 'css/oap.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">



    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=SUSE">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=SUSE:wght@100..800&display=swap" rel="stylesheet">

    {% block extra_css %}
    {# Override this in templates to add extra stylesheets #}
    {% endblock %}
</head>

<body class="{% block body_class %}{% endblock %}">

    {% block content %}{% endblock %}

    {# Global javascript #}
    <script type="text/javascript" src="{% static 'js/oap.js' %}"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js"
        integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js"
        integrity="sha384-0pUGZvbkm6XF6gxjEnlmuGrJXVbNuzT9qBBavbLwCsOGabYfZo0T0to5eqruptLy"
        crossorigin="anonymous"></script>
    {% block extra_js %}
    {# Override this in templates to add extra javascript #}
    {% endblock %}
</body>

</html>

oap/templates/wagtailusers/users/create.html
{% extends "wagtailusers/users/edit.html" %}

{% block extra_fields %}
    <li>{% include "wagtailadmin/shared/field.html" with field=form.country %}</li>
{#    <li>{% include "wagtailadmin/shared/field.html" with field=form.status %}</li>#}
{% endblock extra_fields %}

oap/templates/wagtailusers/users/edit.html
{% extends "wagtailusers/users/edit.html" %}

{% block extra_fields %}
    <li>{% include "wagtailadmin/shared/field.html" with field=form.country %}</li>
{#    <li>{% include "wagtailadmin/shared/field.html" with field=form.status %}</li>#}
{% endblock extra_fields %}

search/templates/search/search.html
{% extends "base.html" %}
{% load static wagtailcore_tags %}

{% block body_class %}template-searchresults{% endblock %}

{% block title %}Search{% endblock %}

{% block content %}
<h1>Search</h1>

<form action="{% url 'search' %}" method="get">
    <input type="text" name="query"{% if search_query %} value="{{ search_query }}"{% endif %}>
    <input type="submit" value="Search" class="button">
</form>

{% if search_results %}
<ul>
    {% for result in search_results %}
    <li>
        <h4><a href="{% pageurl result %}">{{ result }}</a></h4>
        {% if result.search_description %}
        {{ result.search_description }}
        {% endif %}
    </li>
    {% endfor %}
</ul>

{% if search_results.has_previous %}
<a href="{% url 'search' %}?query={{ search_query|urlencode }}&amp;page={{ search_results.previous_page_number }}">Previous</a>
{% endif %}

{% if search_results.has_next %}
<a href="{% url 'search' %}?query={{ search_query|urlencode }}&amp;page={{ search_results.next_page_number }}">Next</a>
{% endif %}
{% elif search_query %}
No results found
{% endif %}
{% endblock %}

tutorial/templates/base.html
{% load static %}
<!DOCTYPE html>
<html dir="ltr" lang="en">
  <head>
    <meta charset="utf-8" />
    <title>{% block title %}django-comments-xtd tutorial{% endblock %}</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Oxygen:wght@300;400;700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-icons/1.11.3/font/bootstrap-icons.min.css" integrity="sha512-dPXYcDub/aeb08c63jRq/k6GaKccl256JQy/AnOq7CAnEZ9FzSL9wSbcZkMp4R26vBsMLFYH4kQ67/bbV8XaCQ==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.3.3/css/bootstrap.min.css" integrity="sha512-jnSuA4Ss2PkkikSOLtYs8BlYIeeIK1h99ty4YfvRPAlzr377vr3CXDb7sb7eEEBYjDtcYj+AjBH3FLv5uSJuXg==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <style>
      html * {

        font-family: Oxygen !important;
      }
      .container {
        width: auto;
        max-width: 680px;
        padding: 0 15px;
      }
      .post-footer, .comments {
        padding: 20px 0;
      }
      #comments .content p:last-child {
        margin-bottom: 0;
      }
    </style>
  </head>
  <body>
    <div class="container">
      <div class="row my-4">
        <div class="col-lg-12">
	      <h5 class="text-center">django-comments-xtd</h5>
          <hr/>
        </div>
      </div>
    </div>

    <div class="container">
      {% block content %}
      {% endblock %}
    </div>

    <div class="container">
      <div class="row">
        <div class="col-lg-12 col-md-12">
          <hr/>
          <p class="text-center text-muted small">django-comments-xtd tutorial.</p>
        </div>
      </div>
    </div>

    {% block extra-js %}
    {% endblock %}
  </body>
</html>

tutorial/templates/blog/post_detail.html
{% extends "base.html" %}

{% block title %}{{ object.title }}{% endblock %}

{% block content %}
<div class="pb-3">
  <h1 class="text-center">{{ object.title }}</h1>
  <p class="small text-center">{{ object.publish|date:"l, j F Y" }}</p>
</div>
<div>
  {{ object.body|linebreaks }}
</div>
<div class="pt-4 text-center">
  <a href="{% url 'blog:post-list' %}">Back to the post list</a>
</div>
{% endblock %}

tutorial/templates/blog/post_list.html
{% extends "base.html" %}

{% block content %}
<h1 class="pb-3 text-center">Blog</h1>

<div class="row justify-content-center flex-fill">
  <div class="col-md-10">
    {% for object in object_list %}
    <h3><a href="{{ object.get_absolute_url }}">{{ object.title }}</a></h3>
    <p class="date">Published {{ object.publish }}</p>
    {{ object.body|truncatewords:30|linebreaks }}
    {% endfor %}
  </div>
</div>

<ul class="mt-5 pagination justify-content-center">
  <li class="page-item{% if not page_obj.has_previous %} disabled{% endif %}">
    <a class="page-link" href="{{ url }}?page={% if page_obj.has_previous %}{{ page_obj.previous_page_number }}{% endif %}">previous</a>
  </li>
  {% for page_number in page_range %}
  <li class="page-item{% if page_number == page_obj.number %} active{% endif %}">
    <a class="page-link" href="{{ url }}?page={{ page_number }}">{{ page_number }}</a>
  </li>
  {% endfor %}
  <li class="page-item{% if not page_obj.has_next %} disabled{% endif %}">
    <a class="page-link" href="{{ url }}?page={% if page_obj.has_next %}{{ page_obj.next_page_number }}{% endif %}">next</a>
  </li>
</ul>
{% endblock %}

tutorial/templates/comments/400-debug.html
{% extends "base.html" %}

{% block title %}Bad request{% endblock %}

{% block content %}
<h3 class="text-center">Comment post not allowed</h3>
<p class="text-center">{{ why }}</p>
<hr/>
<p class="col-lg-offset-1 col-md-offset-1 text-muted">
  You're seeing this error because you have <code>DEBUG = True</code> in
  your Django settings file. Change that to <code>False</code>, and Django
  will display a standard 400 error page.
</p>
{% endblock %}

tutorial/templates/home.html
{% extends "base.html" %}

{% block content %}
<h1 class="pb-3 text-center">tutorial</h1>

<div class="row justify-content-center flex-fill">
  <div class="col-md-10">
    <p class="lead">Contains a simple <code>blog</code> application with a <code>Post</code> model to which we will add comments by using <strong>django-contrib-comments</strong> and <strong>django-comments-xtd</strong>.</p>
    <p class="my-3 text-center">Continue to the <a href="{% url 'blog:post-list' %}">blog</a>.</p>
  </div>
</div>
{% endblock %}